// js/config.js — LOCAL DEVELOPMENT placeholder
// Replace with real values from your Supabase project settings.
// Production: this file is auto-generated by scripts/inject-config.js during build.
window.SUPABASE_URL = 'https://wvkkgjqxqikamrmpfksc.supabase.co';
window.SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind2a2tnanF4cWlrYW1ybXBma3NjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzcxNTIwNDUsImV4cCI6MjA5MjcyODA0NX0.QwUKrIv2lN02aYJPQbiI0Z14BvjihgPm-uOa9ov18d0';
