// scripts/inject-config.js
// Generates js/config.js from environment variables at build time.
// Run: node scripts/inject-config.js

const fs = require('fs');
const path = require('path');

const url = process.env.SUPABASE_URL || 'https://YOUR-REF.supabase.co';
const key = process.env.SUPABASE_ANON_KEY || 'YOUR_ANON_KEY';

const content = `// Auto-generated by scripts/inject-config.js — do not edit manually
window.SUPABASE_URL = ${JSON.stringify(url)};
window.SUPABASE_ANON_KEY = ${JSON.stringify(key)};
`;

const dir = path.join(__dirname, '..', 'js');
if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
fs.writeFileSync(path.join(dir, 'config.js'), content);
console.log('✓ js/config.js written');
